### ISSUE TITLE
uninitialized constant ActionController::Response

### ISSUE THREAD

**Issue by fgaudreau** [oggy/template_streaming#1]
Hi oggy, great project.

after:  script/plugin install git://github.com/oggy/template_streaming.git
and:    Class ApplicationController ... include TemplateStreaming
server fails to start
I get:  uninitialized constant ActionController::Response
in: Rails 2.3.5
with: Ruby  1.8.6

please be lenient if this is only a newbie mistake

Francois

**Comment by oggy** [comment]
Hi Francois,

There should be no need to include TemplateStreaming into your
controller - the plugin mixes various modules into the Rails
framework and it all happens when you "require
'template_streaming'". I can add options to selectively enable or
disable progressive rendering on a per-action basis if necessary.

If you use Bundler [http://github.com/carlhuda/bundler], simply
declare the template_streaming gem dependency and you should be
good to go. Bundler tends to be more in vogue these days rather
than plugins, as aside from ensuring dependencies get resolved
correctly, it means you don't need to bloat your repository with
as much third-party code, and you can easily see which versions
of which gem your app depends upon.

Nevertheless, should you choose to keep using this as a plugin,
I've added a rails/init.rb script to the repo, so if you update
your plugin it should now work. Let me know how it goes.

Thanks!
George.
